repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-ast
    - id: check-merge-conflict
    - id: check-xml
    - id: end-of-file-fixer
    - id: name-tests-test
    - id: trailing-whitespace

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.1
  hooks:
    - id: insert-license
      files: \.py
      args: ['--license-filepath', 'LICENSE.header', '--use-current-year']

- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.9.1
  hooks:
    - id: black

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.270
  hooks:
    - id: ruff

- repo: https://github.com/python-poetry/poetry
  rev: '1.5.0'
  hooks:
    - id: poetry-check
    - id: poetry-lock
      args: ['--check']
