name: Run checks and tests

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
        poetry-version: ["1.5.0"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install package via Poetry
        run: poetry install
      - name: Run pre-commit hooks
        run: poetry run pre-commit run --all-files
      - name: Run Python tests
        run: poetry run pytest --cov=acl_anthology --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
